spring.datasource.url=jdbc:postgresql://localhost:5432/flowcare_dev
spring.datasource.username=flowadmin
spring.datasource.password=flowpass

# Hibernate will update the schema automatically in dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true